name: PR Checklist Validator

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body contains checked items
        uses: actions/github-script@v7
        with:
          script: |
            const checklist = [
              "- [x] Impact Assessment",
              "- [x] Performance Checklist",
              "- [x] Quality Checklist",
              "- [x] SOLID Checklist"
            ];

            const body = context.payload.pull_request.body || "";
            let missing = [];

            checklist.forEach(item => {
              if (!body.includes(item)) {
                missing.push(item);
              }
            });

            if (missing.length > 0) {
              core.setFailed(`❌ PR checklist incomplete. Missing:\n${missing.join("\n")}`);
            } else {
              core.info("✅ All checklist items are completed!");
            }
